"""THE RULE: no optional step may ever cost the deliverable.

Tested as a property of the pipeline rather than of any particular step,
because the failure mode belongs to Siril -- it aborts a script on the first
failed command -- and therefore to every optional step that will ever be
added. Three separate instances of this reached real data before it was
fixed in one place:

  * a preview JPEG whose folder was missing stopped every layer running;
  * a plate solve that could not succeed on wide-angle frames took
    background removal, colour calibration, denoise and star reduction with
    it;
  * and both were reported as failed runs when the stack was already saved.

The important test here is the LAST one, which breaks an arbitrary optional
step by name and asserts that the deliverable still lands and the other
optional steps still ran. It knows nothing about which extras exist, so it
keeps working for extras that have not been written yet.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

sys.path.insert(0, str(Path(__file__).resolve().parent))

from dwarf2siril.pipeline import OPTIONAL, REQUIRED, split

SCRIPT = """\
# Siril script generated by Dwarf2Siril for NGC 7000
requires 1.4.0
cd "/out"
set32bits
setext fit

# @@SEGMENT required

convert light -out=../process
stack r_light rej w 3 3 -out=../STACK

# @@SEGMENT optional Background removal
subsky -rbf
save STACK_processed

# @@SEGMENT optional Denoising
denoise -nocosmetic
save STACK_processed
"""


class SplitTests(unittest.TestCase):
    def test_the_preamble_is_repeated_into_every_segment(self) -> None:
        """Each segment is its own Siril, and a fresh Siril knows nothing.

        It has to be told the working directory and the bit depth again, or
        the second step runs in the wrong folder.
        """
        preamble, segments = split(SCRIPT)
        for segment in segments:
            text = segment.script(preamble)
            self.assertIn('cd "/out"', text)
            self.assertIn("set32bits", text)

    def test_segments_come_out_in_order_and_labelled(self) -> None:
        _preamble, segments = split(SCRIPT)
        self.assertEqual(
            [(REQUIRED, ""), (OPTIONAL, "Background removal"), (OPTIONAL, "Denoising")],
            [(s.kind, s.label) for s in segments],
        )

    def test_a_script_with_no_markers_is_one_required_piece(self) -> None:
        """An older script, or one the user wrote, runs and is judged as one."""
        _preamble, segments = split("requires 1.4.0\nstack whatever\n")
        self.assertEqual(1, len(segments))
        self.assertEqual(REQUIRED, segments[0].kind)
        self.assertFalse(segments[0].optional)

    def test_the_markers_are_comments_so_the_script_still_runs_by_hand(self) -> None:
        """There is ONE script. The user's copy is the copy that runs.

        If the markers were anything but comments there would have to be two
        representations, and two representations drift.
        """
        for line in SCRIPT.splitlines():
            if "@@SEGMENT" in line:
                self.assertTrue(line.strip().startswith("#"))


class RuleTests(unittest.TestCase):
    """The rule itself, exercised end to end against a real Siril."""

    def setUp(self) -> None:
        from dwarf2siril.siril import find_siril

        self.siril = find_siril()
        if self.siril is None:
            self.skipTest("Siril is not installed on this machine")
        self._tmp = TemporaryDirectory()
        self.out = Path(self._tmp.name)
        from test_core import write_fits

        write_fits(self.out / "SOURCE.fits", EXPTIME=1.0, GAIN=0)

    def tearDown(self) -> None:
        self._tmp.cleanup()

    def _run(self, script: str) -> tuple[list[str], int]:
        from dwarf2siril.siril import stream_plan

        path = self.out / "run.ssf"
        path.write_text(script, encoding="utf-8")
        lines: list[str] = []
        code = 0
        for item in stream_plan(path, self.siril):
            if item.startswith("__RESULT__:"):
                code = int(item.split(":", 1)[1])
                continue
            lines.append(item)
        return lines, code

    def _script(self, broken: str = "") -> str:
        """A tiny pipeline: make a file, then three optional steps on it.

        ``broken`` names the optional step to sabotage. The sabotage is a
        command that cannot work, which is exactly what a real failing extra
        looks like to Siril.
        """
        def step(label: str) -> str:
            command = (
                "load nonexistent_image_that_cannot_be_loaded"
                if label == broken
                else f"load DELIVERABLE\nsave RAN_{label.replace(' ', '_')}"
            )
            return f"\n# @@SEGMENT optional {label}\n{command}\n"

        cd = str(self.out).replace("\\", "/")
        return (
            f'requires 1.4.0\ncd "{cd}"\nset32bits\nsetext fit\n'
            "\n# @@SEGMENT required\n"
            # Siril refuses to CREATE an image from a script, so the
            # deliverable is made by loading a real frame and saving it.
            "load SOURCE.fits\nsave DELIVERABLE\n"
            + step("Alpha") + step("Beta") + step("Gamma")
        )

    def test_a_failing_optional_step_costs_nothing_but_itself(self) -> None:
        """The whole rule, in one assertion set.

        Deliberately breaks an arbitrary optional step by name rather than
        any real one, so this keeps testing the rule for extras that do not
        exist yet.
        """
        lines, code = self._run(self._script(broken="Beta"))

        self.assertEqual(0, code, "an optional failure must not fail the run")
        self.assertTrue(
            (self.out / "DELIVERABLE.fit").is_file(),
            "the deliverable was not produced",
        )
        # The steps either side of the broken one both ran.
        self.assertTrue((self.out / "RAN_Alpha.fit").is_file(), "the step before")
        self.assertTrue(
            (self.out / "RAN_Gamma.fit").is_file(),
            "a later optional step was taken down with the failing one",
        )
        self.assertFalse((self.out / "RAN_Beta.fit").is_file())

        # And the user is told which one, by name.
        skipped = [line for line in lines if line.startswith("__SKIPPED__:")]
        self.assertEqual(1, len(skipped), skipped)
        self.assertIn("Beta", skipped[0])

    def test_the_skip_reaches_the_result_not_just_the_log(self) -> None:
        from dwarf2siril.siril import interpret

        lines, code = self._run(self._script(broken="Beta"))
        result = interpret(lines, code, self.out / "DELIVERABLE.fit")
        self.assertTrue(result.ok)
        self.assertTrue(result.warnings)
        self.assertIn("Beta", result.warnings[0])

    def test_a_failing_REQUIRED_step_is_still_a_failure(self) -> None:
        """Not everything is forgiven. If the stack cannot be built, say so."""
        cd = str(self.out).replace("\\", "/")
        lines, code = self._run(
            f'requires 1.4.0\ncd "{cd}"\nset32bits\nsetext fit\n'
            "\n# @@SEGMENT required\n"
            "load nonexistent_image_that_cannot_be_loaded\n"
            "\n# @@SEGMENT optional Alpha\nload SOURCE.fits\nsave RAN_Alpha\n"
        )
        self.assertNotEqual(0, code)
        self.assertFalse(
            (self.out / "RAN_Alpha.fit").is_file(),
            "a required failure must stop the run, not carry on regardless",
        )

    def test_every_optional_step_the_generator_emits_is_marked(self) -> None:
        """A new extra inherits the rule by being emitted between markers.

        This is what stops the next one being another separate fix: if a
        layer is added without a marker, its commands land in whatever
        segment precedes it and this notices.
        """
        from dwarf2siril.postprocess import PostOptions
        from dwarf2siril.script import _post_processing_lines

        options = PostOptions(
            background_removal=True, plate_solve=True, colour_calibration=True,
            denoise=True, star_reduction=True, starnet_path=Path("/fake/starnet2.exe"),
        )
        text = "\n".join(_post_processing_lines("STACK", options))
        _preamble, segments = split("# @@SEGMENT required\n" + text)

        labels = [s.label for s in segments if s.optional]
        for expected in ("Background removal", "Plate solving", "Colour calibration",
                         "Denoising", "Star reduction"):
            self.assertIn(expected, labels)

        # And no LAYER command sits outside an optional segment. The
        # required part may of course contain required work -- it makes the
        # working copy -- but a layer landing there would run unprotected,
        # which is precisely the bug this whole arrangement exists to stop.
        layers = ("subsky", "platesolve", "pcc", "denoise", "starnet", "pm ", "savejpg")
        stray = [
            line.strip()
            for segment in segments
            if segment.kind == REQUIRED
            for line in segment.lines
            if line.strip().startswith(layers)
        ]
        self.assertEqual([], stray, f"layer commands outside a segment: {stray}")


if __name__ == "__main__":
    unittest.main()
